
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '**'
        
env:
    APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    APPLITOOLS_BATCH_NAME: ${{ github.ref }}
    APPLITOOLS_BATCH_ID: ${{ github.event.pull_request.head.sha || github.sha }}
    APPLITOOLS_BRANCH_NAME: ${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-content:
    runs-on: ubuntu-latest
      - name: Extract branch name
        shell: bash
        run: echo BRANCH_NAME="##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
